packages:
  - docs
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  core-js-pure: true
  esbuild: true
  sqlite3: true
  better-sqlite3: true
  unrs-resolver: true

catalog:
  typescript: ^7.0.0
  vue: ^3.5.29
  vite: 8.1.4

enableGlobalVirtualStore: true

overrides:
  # FIXME: vulnerable
  '@cloudbase/database>lodash.unset': ^4.18.0
  # FIXME: vulnerable
  '@cloudbase/node-sdk>axios': ^0.33.0
  # FIXME: https://github.com/next-theme/utils/issues/42
  '@next-theme/utils>js-yaml': ^5.0.0
  '@waline/api': workspace:*
  '@waline/client': workspace:*
  '@xmldom/xmldom': ^0.9.10
  # FIXME: vulnerable
  'apidoc>esbuild-loader': ^4.4.3

patchedDependencies:
  apidoc: patches/apidoc.patch

packageExtensions:
  # FIXME: This is a bug in mathjax
  '@mathjax/mathjax-newcm-font':
    peerDependencies:
      '@mathjax/src': ^4.1.2

  # FIXME: This is a bug in mathjax
  '@mathjax/mathjax-tex-font':
    peerDependencies:
      '@mathjax/src': ^4.1.2

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1 # babel
  - undici@5.29.0 # vercel
  - undici-types@6.21.0 # node types
