name: 'publish @waline/api'

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/release-api.yml
      - packages/api/**

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/setup@v3
        with:
          runtime: node@^24.20.0

      - name: Install Dependencies
        run: pnpm ci

      - name: Build API
        run: pnpm run api:build

      - name: Publish
        run: pnpm publish -r --filter @waline/api --no-git-checks
